env:
  MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard
    -Dmaven.wagon.http.retryHandler.count=3
jobs:
  check:
    name: Check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Check license header
      run: docker run --rm -v $(pwd):/github/workspace ghcr.io/korandoru/hawkeye-native:v3
        check
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      name: Check code style
      run: ./mvnw spotless:check
  required:
    if: ${{ always() }}
    name: Required
    needs:
    - check
    - unittest
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Guardian
      run: "if [[ ! ( \\\n       \"${{ needs.check.result }}\" == \"success\" \\\n\
        \    && \"${{ needs.unittest.result }}\" == \"success\" \\\n    ) ]]; then\n\
        \  echo \"Required jobs haven't been completed successfully.\"\n  exit -1\n\
        fi\n"
  unittest:
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    name: Unit tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Cache Local Maven Repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with ${{ matrix.java }}
      run: ./mvnw clean install -DskipTests
    - continue-on-error: true
      name: Test with ${{ matrix.java }}
      run: ./mvnw verify
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 17
        - 21
    timeout-minutes: 180
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
